spring:
  application:
    name: checkout-service

  # ── JPA / Hibernate ──
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ── DataSource ──
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # ── Kafka ──
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# ── Server ──
server:
  port: 8085

# ── Actuator ──
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

external:
  order-service:
    base-url: http://localhost:8083