version: '3.8'

services:


  # ========================
  # Microservices
  # ========================

  tenant-service:
    build:
      context: ./tenant-service
      dockerfile: dockerfile
    container_name: fintech-tenant-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/tenant_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root # Change to your pgAdmin password
    networks:
      - fintech-network

  merchant-service:
    build:
      context: ./merchant-service
      dockerfile: dockerfile
    container_name: fintech-merchant-service
    ports:
      - "8082:8082"
    environment:
      EXTERNAL_TENANT_SERVICE_BASE_URL: http://tenant-service:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/merchant_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root # Change to your pgAdmin password
    networks:
      - fintech-network

  order-service:
    build:
      context: ./order-service
      dockerfile: dockerfile
    container_name: fintech-order-service
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      EXTERNAL_MERCHANT_SERVICE_BASE_URL: http://merchant-service:8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/order_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root # Change to your pgAdmin password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - fintech-network

  checkout-service:
    build:
      context: ./checkout-service
      dockerfile: dockerfile
    container_name: fintech-checkout-service
    depends_on:
      - kafka
    ports:
      - "8085:8085"
    environment:
      EXTERNAL_ORDER_SERVICE_BASE_URL: http://order-service:8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/checkout_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root # Change to your pgAdmin password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - fintech-network


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - kafka
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/payment_db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  connector-service:
    build: ./connector-service
    container_name: connector-service
    depends_on:
      - kafka
    ports:
      - "8086:8086"
    environment:
      SERVER_PORT: 8086
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  webhook-service:
    build: ./webhook-service
    container_name: webhook-service
    depends_on:
      - kafka
    ports:
      - "8087:8087"
    environment:
      SERVER_PORT: 8087
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/webhook_db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

# ========================
# Networks
# ========================

networks:
  fintech-network:
    driver: bridge