spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: webhook-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
  h2:
    console:
      enabled: true

  server:
    port: ${SERVER_PORT:8082}

  webhook:
    verify-token: ${WEBHOOK_VERIFY_TOKEN:}
    signing-secret: ${WEBHOOK_SIGNING_SECRET:}

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual
    consumer:
      group-id: fintech-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.HashMap
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
